サインアップ機能
shinonome-inc/backend-final-assignment-Kotaro pull request #1
Opened 2024-11-09 16:17 UTC by Kotaro0722

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-11-11 07:40 UTC, harune-pg requested changes
最終課題の最初のステップ、画面と機能が要件通り実装できていてよかったです👍
いくつか修正点がありますので、ご確認お願いします🙏

2024-11-11 07:40 UTC, harune-pg commented on accounts/views.py
> +        print(self.object)
使っていないprint文は削除しておきましょう🗑️

2024-11-11 07:40 UTC, harune-pg commented on tweets/views.py
>  # from django.shortcuts import render
使わなかったモジュールは消して大丈夫です！

2024-11-11 07:40 UTC, harune-pg commented on accounts/tests.py
> +        self.assertFalse(User.objects.filter(email=invalid_data["username"]).exists())
63行目の`filter`で`email`と`username`を比較しているため、意図したチェックになっていないかもしれません。
他にも同様の箇所があるので、このファイル全体を見直してみてください！

具体的には、`username`フィールドがユニークなので、`username`でフィルターするといいです！

詳しい説明は、[Wikiのサインアップ機能のページ](https://shinonome-inc.notion.site/b6ce37a837614e03b8d6eb726a3338e0)のSTEP5の04.の`3. postのテスト`の`def test_success_post(self)の詳しい説明`の`3. self.assertTrue … の説明`にあります。

2024-11-12 01:17 UTC, harune-pg reviewed
前回の3つの修正点については問題なく対応されていて、OKでした！🙌
その上で、新たに修正点が見つかったので確認をお願いします🙏

2024-11-12 01:17 UTC, harune-pg commented on accounts/tests.py
> +        self.assertIn("同じユーザー名が既に登録済みです。", form.errors["username"])
`test_failure_post_with_duplicated_user`メソッドで、期待する効果「DBにレコードが追加されていないこと」のチェックが抜けているようです。

2024-11-12 01:17 UTC, harune-pg commented on accounts/tests.py
> +        self.assertIn("このフィールドは必須です。", form.errors["password2"])
【提案（必須じゃない）】
`password2`に変えるなら、`password1`でも同じformエラーが出てるので、どっちも書いちゃってもいいかもです！

2024-11-12 01:51 UTC, harune-pg approved these changes
LGTM！
参考程度に、1件だけコメントをつけておきました。
<img src="https://looks-to.me/images/posts/xx2esde2r7d6jq8ipdicvou7" height=150/>

2024-11-12 01:51 UTC, harune-pg commented on accounts/tests.py
> +        self.assertEqual(User.objects.filter(username=duplicated_data["username"]).count(), 1)
【提案（必須じゃない）】
やっていることは変わりませんが、`valid_data["username"]`を使った方が意味的に自然かと思います。こんな感じで修正してみてはいかがでしょうか？
```suggestion
        self.assertEqual(User.objects.filter(username=valid_data["username"]).count(), 1)
```

2024-11-12 14:56 UTC, tak848 approved these changes
LGTM!

2024-11-13 06:27 UTC, merged